const express = require('express');
const router = express.Router();
const hackathonController = require('../controllers/hackathonController');
const requireAuth = require('../middleware/requireAuth');
const requireAdmin = require('../middleware/requireAdmin');
router.get('/', hackathonController.getHackathons);
router.get('/:id', hackathonController.getHackathonById);
router.post('/', requireAuth, requireAdmin, hackathonController.createHackathon);
router.put('/:id', requireAuth, requireAdmin, hackathonController.updateHackathon);
router.delete('/:id', requireAuth, requireAdmin, hackathonController.deleteHackathon);
module.exports = router;